//
// GENERATED by ll1gen : Do not modify (or on your own risk)
//
#ifndef _LL1GEN_HELLOBEAN_HPP_
#define _LL1GEN_HELLOBEAN_HPP_

#include "json_utils.hpp"

//ll1gen::include_begin

//ll1gen::include_end

namespace helloworld { 

class HelloBean {
public:
    //ll1gen::constructor_begin
    HelloBean(
    		    const std::string & __fname

,
    const std::string & __lname

,
     unsigned int  __age

//ll1gen::constructor_param
              ) :
    		    _fname(__fname)

,
    _lname(__lname)

,
    _age(__age)

//ll1gen::constructor_assign
		{}
    //ll1gen::constructor_begin

    //ll1gen::copy_constructor_begin
    HelloBean(const HelloBean & __bean) :
    		    _fname(__bean._fname)

,
    _lname(__bean._lname)

,
    _age(__bean._age)

//ll1gen::copy_constructor_assign
		{}
    //ll1gen::copy_constructor_end

    HelloBean() {}
    virtual ~HelloBean() {}

    //ll1gen::getters_begin

    
    const std::string & getFname() const { return _fname; }

    void setFname( const std::string & __val) { _fname = __val; }



    const std::string & getLname() const { return _lname; }

    void setLname( const std::string & __val) { _lname = __val; }



    const unsigned int & getAge() const { return _age; }

    void setAge(  unsigned int  __val) { _age = __val; }


//ll1gen::getters_end

    HelloBean & operator = (const HelloBean & __bean) {
        if(this != &__bean) {
    		//ll1gen::opeq_end
        }
        return (*this);
    }

    friend std::ostream& operator<< (std::ostream& __stream, const HelloBean& __bean);
    friend std::istream& operator>> (std::istream& __stream, HelloBean& __bean);
private:
    //ll1gen::field_decl_begin

    std::string _fname;
std::string _lname;
unsigned int _age;
//ll1gen::field_decl_end
};

std::ostream& operator<< (std::ostream& __stream, const HelloBean& __bean) {
    __stream << "{";
    //ll1gen::field_ostream_begin

        __stream << "\"fname\":\"" << ll1gen::json::detail::encodeJsonString(__bean._fname) << "\"";


__stream << ",";
    __stream << "\"lname\":\"" << ll1gen::json::detail::encodeJsonString(__bean._lname) << "\"";


__stream << ",";
    __stream << "\"age\":" << __bean._age;


//ll1gen::field_ostream_end
    __stream << "}";
    return __stream;
}

std::istream& operator>> (std::istream& __stream, HelloBean& __bean) {
    char __startObjectMrk = ll1gen::json::detail::lookUpAndEat(__stream, "{n");
    if(__startObjectMrk == 'n') {
        ll1gen::json::detail::lookUpTokenRemainder(__stream, __startObjectMrk, "null");
        return __stream;
    }
    for(unsigned int __i = 0; __i < 3; ++__i) {
        ll1gen::json::detail::lookUpAndEat(__stream, "\"");
        std::string __propertyName = ll1gen::json::detail::lookUp(__stream, "\"");
        ll1gen::json::detail::lookUpAndEat(__stream, ":");

        //ll1gen::field_istream_begin

            if(__propertyName == "fname") {
        if(!ll1gen::json::detail::parseString(__stream, __bean._fname)) {
            throw new std::runtime_error("JSON: null not supported for field fname (string). Check definition.");
        }
    }

else
    if(__propertyName == "lname") {
        if(!ll1gen::json::detail::parseString(__stream, __bean._lname)) {
            throw new std::runtime_error("JSON: null not supported for field lname (string). Check definition.");
        }
    }

else
    if(__propertyName == "age") {
        if(!ll1gen::json::detail::lookUpNull(__stream)) {
            __stream >> __bean._age;
        } else {
            throw std::runtime_error("JSON: null not supported for field age. Check definition");
        }
    }

//ll1gen::field_istream_end

        if('}' == ll1gen::json::detail::lookUpAndEat(__stream, "},")) {
            break;
        }
    }
    return __stream;
}

} 

#endif
