//
// GENERATED by ll1gen : Do not modify (or on your own risk)
//
#ifndef _LL1GEN_TEST2MULTI_HPP_
#define _LL1GEN_TEST2MULTI_HPP_

#include "json_utils.hpp"

//ll1gen::include_begin

#include "test2simple.hpp"
//ll1gen::include_end

namespace test { 

class Test2Multi {
public:
    //ll1gen::constructor_begin

    //ll1gen::constructor_end
    Test2Multi() {}
    ~Test2Multi() {}

#ifndef LL1GEN_DISABLE_STANDARD_GETTERS
    //ll1gen::getters_begin

    
    std::vector<bool>  get_multiBool() const { return _multiBool; }

    void set_multiBool( const std::vector<bool>  & __val) { _multiBool = __val; }



    std::vector<std::string>  get_multiString() const { return _multiString; }

    void set_multiString( const std::vector<std::string>  & __val) { _multiString = __val; }



    std::vector<int>  get_multiInt() const { return _multiInt; }

    void set_multiInt( const std::vector<int>  & __val) { _multiInt = __val; }



    std::vector<Test2Simple>  get_multiObj() const { return _multiObj; }

    void set_multiObj( const std::vector<Test2Simple>  & __val) { _multiObj = __val; }


//ll1gen::getters_end
#endif

#ifndef LL1GEN_DISABLE_REFERENCE_GETTERS
    //ll1gen::ref_getters_begin

        std::vector<bool>  & multiBool() { return _multiBool; }


    std::vector<std::string>  & multiString() { return _multiString; }


    std::vector<int>  & multiInt() { return _multiInt; }


    std::vector<Test2Simple>  & multiObj() { return _multiObj; }


//ll1gen::ref_getters_end
#endif

    friend std::ostream& operator<< (std::ostream& __stream, const Test2Multi& __bean);
    friend std::istream& operator>> (std::istream& __stream, Test2Multi& __bean);
private:
    //ll1gen::field_decl_begin

    std::vector<bool>  _multiBool;
std::vector<std::string>  _multiString;
std::vector<int>  _multiInt;
std::vector<Test2Simple>  _multiObj;
//ll1gen::field_decl_end
};

std::ostream& operator<< (std::ostream& __stream, const Test2Multi& __bean) {
    __stream << "{";
    //ll1gen::field_ostream_begin

        __stream << "\"multiBool\":";
    ll1gen::json::serializeVector(__stream, __bean._multiBool);


__stream << ",";
    __stream << "\"multiString\":";
    ll1gen::json::serializeVector(__stream, __bean._multiString);


__stream << ",";
    __stream << "\"multiInt\":";
    ll1gen::json::serializeVector(__stream, __bean._multiInt);


__stream << ",";
    __stream << "\"multiObj\":";
    ll1gen::json::serializeVector(__stream, __bean._multiObj);


//ll1gen::field_ostream_end
    __stream << "}";
    return __stream;
}

std::istream& operator>> (std::istream& __stream, Test2Multi& __bean) {
    char __startObjectMrk = ll1gen::json::detail::lookUpAndEat(__stream, "{n");
    if(__startObjectMrk == 'n') {
        ll1gen::json::detail::lookUpTokenRemainder(__stream, __startObjectMrk, "null");
        return __stream;
    }
    for(unsigned int __i = 0; __i < 4; ++__i) {
        ll1gen::json::detail::lookUpAndEat(__stream, "\"");
        std::string __propertyName = ll1gen::json::detail::lookUp(__stream, "\"");
        ll1gen::json::detail::lookUpAndEat(__stream, ":");

        //ll1gen::field_istream_begin

            
    if(__propertyName == "multiBool") {
        ll1gen::json::deserializeVector(__stream, __bean._multiBool);
    }

else
    
    if(__propertyName == "multiString") {
        ll1gen::json::deserializeVector(__stream, __bean._multiString);
    }

else
    
    if(__propertyName == "multiInt") {
        ll1gen::json::deserializeVector(__stream, __bean._multiInt);
    }

else
    
    if(__propertyName == "multiObj") {
        ll1gen::json::deserializeVector(__stream, __bean._multiObj);
    }

//ll1gen::field_istream_end

        if('}' == ll1gen::json::detail::lookUpAndEat(__stream, "},")) {
            break;
        }
    }
    return __stream;
}

} 

#endif
