//
// GENERATED by ll1gen : Do not modify (or on your own risk)
//
#ifndef _LL1GEN_GLOSSARYROOT_HPP_
#define _LL1GEN_GLOSSARYROOT_HPP_

#include "json_utils.hpp"

//ll1gen::include_begin

#include "glossary.hpp"
//ll1gen::include_end

namespace test { namespace glossary { 

class GlossaryRoot {
public:
    //ll1gen::constructor_begin
    GlossaryRoot(
    		    const Glossary & __glossary

//ll1gen::constructor_param
              ) :
    		    _glossary(__glossary)

//ll1gen::constructor_assign
		{}
    //ll1gen::constructor_begin

    //ll1gen::copy_constructor_begin
    GlossaryRoot(const GlossaryRoot & __bean) :
    		    _glossary(__bean._glossary)

//ll1gen::copy_constructor_assign
		{}
    //ll1gen::copy_constructor_end

    GlossaryRoot() {}
    virtual ~GlossaryRoot() {}

    //ll1gen::getters_begin

    
    inline
    const Glossary & getGlossary() const { return _glossary; }

    inline
    void setGlossary( const Glossary & __val) { _glossary = __val; }


//ll1gen::getters_end

    GlossaryRoot & operator = (const GlossaryRoot & __bean) {
        if(this != &__bean) {
    		    this->_glossary = __bean._glossary;

//ll1gen::opeq_assign
        }
        return (*this);
    }

    friend std::ostream& operator<< (std::ostream& __stream, const GlossaryRoot& __bean);
    friend std::istream& operator>> (std::istream& __stream, GlossaryRoot& __bean);
private:
    //ll1gen::field_decl_begin

    Glossary _glossary;
//ll1gen::field_decl_end
};

inline std::ostream& operator<< (std::ostream& __stream, const GlossaryRoot& __bean) {
    __stream << "{";
    //ll1gen::field_ostream_begin

        __stream << "\"glossary\":" << __bean._glossary;


//ll1gen::field_ostream_end
    __stream << "}";
    return __stream;
}

inline std::istream& operator>> (std::istream& __stream, GlossaryRoot& __bean) {
    char __startObjectMrk = ll1gen::json::detail::lookUpAndEat(__stream, "{n");
    if(__startObjectMrk == 'n') {
        ll1gen::json::detail::lookUpTokenRemainder(__stream, __startObjectMrk, "null");
        return __stream;
    }
    for(unsigned int __i = 0; __i < 1; ++__i) {
        ll1gen::json::detail::lookUpAndEat(__stream, "\"");
        std::string __propertyName = ll1gen::json::detail::lookUp(__stream, "\"");
        ll1gen::json::detail::lookUpAndEat(__stream, ":");

        //ll1gen::field_istream_begin

            if(__propertyName == "glossary") {
        if(!ll1gen::json::detail::lookUpNull(__stream)) {
            __stream >> __bean._glossary;
        } else {
            throw std::runtime_error("JSON: null not supported for field glossary. Check definition");
        }
    }

//ll1gen::field_istream_end

        if('}' == ll1gen::json::detail::lookUpAndEat(__stream, "},")) {
            break;
        }
    }
    return __stream;
}

} } 

#endif
