//
// GENERATED by ll1gen : Do not modify (or on your own risk)
//
#ifndef _LL1GEN_GLOSSARYROOT_HPP_
#define _LL1GEN_GLOSSARYROOT_HPP_

#include "json_utils.hpp"

//ll1gen::include_begin

#include "glossary.hpp"
//ll1gen::include_end

namespace test { namespace glossary { 

class GlossaryRoot {
public:
    //ll1gen::constructor_begin

    //ll1gen::constructor_end
    GlossaryRoot() {}
    ~GlossaryRoot() {}

#ifndef LL1GEN_DISABLE_STANDARD_GETTERS
    //ll1gen::getters_begin

    
    Glossary get_glossary() const { return _glossary; }

    void set_glossary( const Glossary & __val) { _glossary = __val; }


//ll1gen::getters_end
#endif

#ifndef LL1GEN_DISABLE_REFERENCE_GETTERS
    //ll1gen::ref_getters_begin

        Glossary & glossary() { return _glossary; }


//ll1gen::ref_getters_end
#endif

    friend std::ostream& operator<< (std::ostream& __stream, const GlossaryRoot& __bean);
    friend std::istream& operator>> (std::istream& __stream, GlossaryRoot& __bean);
private:
    //ll1gen::field_decl_begin

    Glossary _glossary;
//ll1gen::field_decl_end
};

std::ostream& operator<< (std::ostream& __stream, const GlossaryRoot& __bean) {
    __stream << "{";
    //ll1gen::field_ostream_begin

        __stream << "\"glossary\":" << __bean._glossary;


//ll1gen::field_ostream_end
    __stream << "}";
    return __stream;
}

std::istream& operator>> (std::istream& __stream, GlossaryRoot& __bean) {
    char __startObjectMrk = ll1gen::json::detail::lookUpAndEat(__stream, "{n");
    if(__startObjectMrk == 'n') {
        ll1gen::json::detail::lookUpTokenRemainder(__stream, __startObjectMrk, "null");
        return __stream;
    }
    for(unsigned int __i = 0; __i < 1; ++__i) {
        ll1gen::json::detail::lookUpAndEat(__stream, "\"");
        std::string __propertyName = ll1gen::json::detail::lookUp(__stream, "\"");
        ll1gen::json::detail::lookUpAndEat(__stream, ":");

        //ll1gen::field_istream_begin

            if(__propertyName == "glossary") {
        if(!ll1gen::json::detail::lookUpNull(__stream)) {
            __stream >> __bean._glossary;
        } else {
            throw std::runtime_error("JSON: null not supported for field glossary. Check definition");
        }
    }

//ll1gen::field_istream_end

        if('}' == ll1gen::json::detail::lookUpAndEat(__stream, "},")) {
            break;
        }
    }
    return __stream;
}

} } 

#endif
