//
// GENERATED by ll1gen : Do not modify (or on your own risk)
//
#ifndef _LL1GEN_GAMERREL_HPP_
#define _LL1GEN_GAMERREL_HPP_

#include "json_utils.hpp"

//ll1gen::include_begin

#include "gamer.hpp"
//ll1gen::include_end

namespace test { namespace gamer { 

class GamerRel {
public:
    //ll1gen::constructor_begin
    GamerRel(
    		    const Gamer & __gamer

,
    const std::vector<unsigned int>  & __enemyIds

,
    const std::vector<double>  & __enemyCoords

,
    const std::string & __description

//ll1gen::constructor_param
              ) :
    		    _gamer(__gamer)

,
    _enemyIds(__enemyIds)

,
    _enemyCoords(__enemyCoords)

,
    _description(__description)

//ll1gen::constructor_assign
		{}
    //ll1gen::constructor_begin

    //ll1gen::copy_constructor_begin
    GamerRel(const GamerRel & __bean) :
    		    _gamer(__bean._gamer)

,
    _enemyIds(__bean._enemyIds)

,
    _enemyCoords(__bean._enemyCoords)

,
    _description(__bean._description)

//ll1gen::copy_constructor_assign
		{}
    //ll1gen::copy_constructor_end

    GamerRel() {}
    virtual ~GamerRel() {}

    //ll1gen::getters_begin

    
    const Gamer & getGamer() const { return _gamer; }

    void setGamer( const Gamer & __val) { _gamer = __val; }



    const std::vector<unsigned int>  & getEnemyIds() const { return _enemyIds; }

    void setEnemyIds( const std::vector<unsigned int>  & __val) { _enemyIds = __val; }



    const std::vector<double>  & getEnemyCoords() const { return _enemyCoords; }

    void setEnemyCoords( const std::vector<double>  & __val) { _enemyCoords = __val; }



    const std::string & getDescription() const { return _description; }

    void setDescription( const std::string & __val) { _description = __val; }


//ll1gen::getters_end

    GamerRel & operator = (const GamerRel & __bean) {
        if(this != &__bean) {
    		    this->_gamer = __bean._gamer;

    this->_enemyIds = __bean._enemyIds;

    this->_enemyCoords = __bean._enemyCoords;

    this->_description = __bean._description;

//ll1gen::opeq_assign
        }
        return (*this);
    }

    friend std::ostream& operator<< (std::ostream& __stream, const GamerRel& __bean);
    friend std::istream& operator>> (std::istream& __stream, GamerRel& __bean);
private:
    //ll1gen::field_decl_begin

    Gamer _gamer;
std::vector<unsigned int>  _enemyIds;
std::vector<double>  _enemyCoords;
std::string _description;
//ll1gen::field_decl_end
};

std::ostream& operator<< (std::ostream& __stream, const GamerRel& __bean) {
    __stream << "{";
    //ll1gen::field_ostream_begin

        __stream << "\"gamer\":" << __bean._gamer;


__stream << ",";
    __stream << "\"enemyIds\":";
    ll1gen::json::serializeVector(__stream, __bean._enemyIds);


__stream << ",";
    __stream << "\"enemyCoords\":";
    ll1gen::json::serializeVector(__stream, __bean._enemyCoords);


__stream << ",";
    __stream << "\"description\":\"" << ll1gen::json::detail::encodeJsonString(__bean._description) << "\"";


//ll1gen::field_ostream_end
    __stream << "}";
    return __stream;
}

std::istream& operator>> (std::istream& __stream, GamerRel& __bean) {
    char __startObjectMrk = ll1gen::json::detail::lookUpAndEat(__stream, "{n");
    if(__startObjectMrk == 'n') {
        ll1gen::json::detail::lookUpTokenRemainder(__stream, __startObjectMrk, "null");
        return __stream;
    }
    for(unsigned int __i = 0; __i < 4; ++__i) {
        ll1gen::json::detail::lookUpAndEat(__stream, "\"");
        std::string __propertyName = ll1gen::json::detail::lookUp(__stream, "\"");
        ll1gen::json::detail::lookUpAndEat(__stream, ":");

        //ll1gen::field_istream_begin

            if(__propertyName == "gamer") {
        if(!ll1gen::json::detail::lookUpNull(__stream)) {
            __stream >> __bean._gamer;
        } else {
            throw std::runtime_error("JSON: null not supported for field gamer. Check definition");
        }
    }

else
    
    if(__propertyName == "enemyIds") {
        ll1gen::json::deserializeVector(__stream, __bean._enemyIds);
    }

else
    
    if(__propertyName == "enemyCoords") {
        ll1gen::json::deserializeVector(__stream, __bean._enemyCoords);
    }

else
    if(__propertyName == "description") {
        if(!ll1gen::json::detail::parseString(__stream, __bean._description)) {
            throw new std::runtime_error("JSON: null not supported for field description (string). Check definition.");
        }
    }

//ll1gen::field_istream_end

        if('}' == ll1gen::json::detail::lookUpAndEat(__stream, "},")) {
            break;
        }
    }
    return __stream;
}

} } 

#endif
