//
// GENERATED by ll1gen : Do not modify (or on your own risk)
//
#ifndef _LL1GEN_MENUROOT_HPP_
#define _LL1GEN_MENUROOT_HPP_

#include "json_utils.hpp"

//ll1gen::include_begin

#include "menu.hpp"
//ll1gen::include_end

namespace test { namespace menu { 

class MenuRoot {
public:
    //ll1gen::constructor_begin
    MenuRoot(
    		    const Menu & __menu

//ll1gen::constructor_param
              ) :
    		    _menu(__menu)

//ll1gen::constructor_assign
		{}
    //ll1gen::constructor_begin

    //ll1gen::copy_constructor_begin
    MenuRoot(const MenuRoot & __bean) :
    		    _menu(__bean._menu)

//ll1gen::copy_constructor_assign
		{}
    //ll1gen::copy_constructor_end

    MenuRoot() {}
    virtual ~MenuRoot() {}

    //ll1gen::getters_begin

    
    inline
    const Menu & getMenu() const { return _menu; }

    inline
    void setMenu( const Menu & __val) { _menu = __val; }


//ll1gen::getters_end

    MenuRoot & operator = (const MenuRoot & __bean) {
        if(this != &__bean) {
    		    this->_menu = __bean._menu;

//ll1gen::opeq_assign
        }
        return (*this);
    }

    friend std::ostream& operator<< (std::ostream& __stream, const MenuRoot& __bean);
    friend std::istream& operator>> (std::istream& __stream, MenuRoot& __bean);
private:
    //ll1gen::field_decl_begin

    Menu _menu;
//ll1gen::field_decl_end
};

inline std::ostream& operator<< (std::ostream& __stream, const MenuRoot& __bean) {
    __stream << "{";
    //ll1gen::field_ostream_begin

        __stream << "\"menu\":" << __bean._menu;


//ll1gen::field_ostream_end
    __stream << "}";
    return __stream;
}

inline std::istream& operator>> (std::istream& __stream, MenuRoot& __bean) {
    char __startObjectMrk = ll1gen::json::detail::lookUpAndEat(__stream, "{n");
    if(__startObjectMrk == 'n') {
        ll1gen::json::detail::lookUpTokenRemainder(__stream, __startObjectMrk, "null");
        return __stream;
    }
    for(unsigned int __i = 0; __i < 1; ++__i) {
        ll1gen::json::detail::lookUpAndEat(__stream, "\"");
        std::string __propertyName = ll1gen::json::detail::lookUp(__stream, "\"");
        ll1gen::json::detail::lookUpAndEat(__stream, ":");

        //ll1gen::field_istream_begin

            if(__propertyName == "menu") {
        if(!ll1gen::json::detail::lookUpNull(__stream)) {
            __stream >> __bean._menu;
        } else {
            throw std::runtime_error("JSON: null not supported for field menu. Check definition");
        }
    }

//ll1gen::field_istream_end

        if('}' == ll1gen::json::detail::lookUpAndEat(__stream, "},")) {
            break;
        }
    }
    return __stream;
}

} } 

#endif
